# Generated by Django 5.2.10 on 2026-01-23 01:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código de Proyecto"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre del Proyecto")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("client_name", models.CharField(max_length=255, verbose_name="Cliente")),
                (
                    "client_contact",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Contacto del Cliente"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email del Cliente"),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Precio Fijo"),
                            ("t_and_m", "Time & Material"),
                            ("hybrid", "Híbrido"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="Tipo de Proyecto",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("planned_end_date", models.DateField(verbose_name="Fecha Planeada de Fin")),
                (
                    "actual_end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Real de Fin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planificación"),
                            ("active", "Activo"),
                            ("on_hold", "En Pausa"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "budget_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Para proyectos de precio fijo: límite máximo del presupuesto",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Presupuesto Límite (USD)",
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Precio acordado con el cliente para proyectos fixed",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Precio Fijo Acordado (USD)",
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimación interna de horas para proyectos fixed",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Horas Estimadas",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tarifa cobrada al cliente por hora trabajada en proyectos T&M",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Tarifa por Hora (USD)",
                    ),
                ),
                (
                    "max_hours_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Límite de horas facturables para proyectos T&M (opcional)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Tope Máximo de Horas",
                    ),
                ),
                (
                    "actual_hours_logged",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total de horas trabajadas registradas",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Horas Registradas",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costo interno acumulado (suma de costos de recursos)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Costo Real (USD)",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total facturado al cliente",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Ingresos Facturados (USD)",
                    ),
                ),
                (
                    "health_score",
                    models.IntegerField(
                        default=100,
                        help_text="Indicador de salud del proyecto (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Score de Salud",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="Nivel de Riesgo",
                    ),
                ),
                (
                    "technologies",
                    models.JSONField(
                        default=list,
                        help_text="Lista de tecnologías del proyecto",
                        verbose_name="Tecnologías Utilizadas",
                    ),
                ),
                (
                    "team_size",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tamaño del Equipo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("repository_url", models.URLField(blank=True, verbose_name="URL del Repositorio")),
                (
                    "documentation_url",
                    models.URLField(blank=True, verbose_name="URL de Documentación"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre de la Etapa")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Orden de ejecución de la etapa", verbose_name="Orden"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Inicio"),
                ),
                (
                    "planned_end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Planeada de Fin"),
                ),
                (
                    "actual_end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Real de Fin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "No Iniciada"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completada"),
                            ("on_hold", "En Pausa"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "estimated_hours_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Suma de horas estimadas de todas las tareas",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Horas Estimadas Totales",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa",
                "verbose_name_plural": "Etapas",
                "ordering": ["project", "order", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título de la Tarea")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimación inicial basada en el rol requerido",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Horas Estimadas",
                    ),
                ),
                (
                    "logged_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Suma de horas registradas en TimeLog",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Horas Registradas",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En Progreso"),
                            ("blocked", "Bloqueada"),
                            ("review", "En Revisión"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Inicio"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Vencimiento"),
                ),
                (
                    "completed_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Completitud"),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Tags para categorización", verbose_name="Etiquetas"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True,
                        help_text="Si esta tarea se factura al cliente",
                        verbose_name="Facturable",
                    ),
                ),
                (
                    "assigned_resource",
                    models.ForeignKey(
                        blank=True,
                        help_text="Persona real asignada para ejecutar esta tarea",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="resources.resource",
                        verbose_name="Recurso Asignado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "required_role",
                    models.ForeignKey(
                        help_text="Rol necesario para esta tarea (usado en estimación)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estimated_tasks",
                        to="resources.role",
                        verbose_name="Rol Requerido",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.stage",
                        verbose_name="Etapa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["stage", "priority", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Horas",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción del Trabajo")),
                (
                    "task_category",
                    models.CharField(blank=True, max_length=100, verbose_name="Categoría de Tarea"),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True,
                        help_text="Si estas horas deben facturarse al cliente",
                        verbose_name="Facturable",
                    ),
                ),
                ("is_invoiced", models.BooleanField(default=False, verbose_name="Facturado")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo interno (resource hourly_cost * hours)",
                        max_digits=10,
                        verbose_name="Costo (USD)",
                    ),
                ),
                (
                    "billable_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto a cobrar al cliente (para T&M)",
                        max_digits=10,
                        null=True,
                        verbose_name="Monto Facturable (USD)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="resources.resource",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Tiempo",
                "verbose_name_plural": "Registros de Tiempo",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Fecha en que se realizó el trabajo", verbose_name="Fecha"
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Horas trabajadas (máx 24 por día)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("24.00")),
                        ],
                        verbose_name="Horas",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Qué se hizo en estas horas",
                        verbose_name="Descripción del Trabajo",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo real: hours × resource.internal_cost (auto-calculado)",
                        max_digits=10,
                        verbose_name="Costo Interno (USD)",
                    ),
                ),
                (
                    "billable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto a cobrar: hours × task.required_role.standard_rate (auto-calculado)",
                        max_digits=10,
                        verbose_name="Monto Facturable (USD)",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Si el registro fue aprobado por el PM",
                        verbose_name="Aprobado",
                    ),
                ),
                (
                    "is_invoiced",
                    models.BooleanField(
                        default=False,
                        help_text="Si ya fue incluido en una factura",
                        verbose_name="Facturado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="resources.resource",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="projects.task",
                        verbose_name="Tarea",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Tiempo",
                "verbose_name_plural": "Registros de Tiempo",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["code"], name="projects_pr_code_80abae_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "is_active"], name="projects_pr_status_163197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["project_type"], name="projects_pr_project_573ce6_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["start_date", "planned_end_date"], name="projects_pr_start_d_319b2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["project", "order"], name="projects_st_project_22c2c2_idx"),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["status"], name="projects_st_status_7a9d7a_idx"),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_stage_name_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["stage", "status"], name="projects_ta_stage_i_ca2e0e_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_resource", "status"], name="projects_ta_assigne_52bf4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["required_role"], name="projects_ta_require_8bd10d_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="projects_ta_due_dat_4757e0_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["project", "date"], name="projects_ti_project_931a2e_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["resource", "date"], name="projects_ti_resourc_f2ea76_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["is_billable", "is_invoiced"], name="projects_ti_is_bill_4958ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["task", "date"], name="projects_ti_task_id_60f435_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["resource", "date"], name="projects_ti_resourc_d1da40_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["is_approved", "is_invoiced"], name="projects_ti_is_appr_67471e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["date"], name="projects_ti_date_5fde8c_idx"),
        ),
    ]
