# Generated by Django 5.2.10 on 2026-01-23 02:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0002_alter_resource_options_remove_resource_full_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ej: PRJ-2026-001",
                        max_length=20,
                        unique=True,
                        verbose_name="Código del Proyecto",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre del Proyecto")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Nombre del Cliente"),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Price"),
                            ("t_and_m", "Time & Materials"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="Tipo de Proyecto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("planning", "Planificación"),
                            ("active", "En Ejecución"),
                            ("on_hold", "En Pausa"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Solo para proyectos Fixed Price",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Precio Fijo Acordado (USD)",
                    ),
                ),
                (
                    "budget_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo máximo permitido para el proyecto",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Límite de Presupuesto Interno (USD)",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tarifa aplicada al cliente en proyectos T&M",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Tarifa por Hora (USD)",
                    ),
                ),
                (
                    "max_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimación de techo para proyectos T&M",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Presupuesto Máximo Estimado (USD)",
                    ),
                ),
                (
                    "profit_margin_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        help_text="Porcentaje de margen esperado",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Margen de Ganancia Objetivo (%)",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Inicio"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Fin Estimada"),
                ),
                (
                    "actual_end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Fin Real"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de etiquetas para categorización",
                        verbose_name="Etiquetas",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas Internas")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: Sprint 1, Fase de Diseño",
                        max_length=200,
                        verbose_name="Nombre de la Etapa",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Orden de ejecución de la etapa", verbose_name="Orden"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planificado"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completado"),
                            ("on_hold", "En Pausa"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Inicio"),
                ),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="Fecha de Fin")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa",
                "verbose_name_plural": "Etapas",
                "ordering": ["project", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título de la Tarea")),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("todo", "Por Hacer"),
                            ("in_progress", "En Progreso"),
                            ("in_review", "En Revisión"),
                            ("blocked", "Bloqueado"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="backlog",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tiempo estimado para completar la tarea",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Horas Estimadas",
                    ),
                ),
                (
                    "logged_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Actualizado automáticamente por TimeLog via signals",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Horas Registradas",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Vencimiento"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Inicio Real"),
                ),
                (
                    "completion_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Completitud"),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="Etiquetas")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "assigned_resource",
                    models.ForeignKey(
                        blank=True,
                        help_text="Persona real asignada (determina el costo interno)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="resources.resource",
                        verbose_name="Recurso Asignado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "required_role",
                    models.ForeignKey(
                        help_text="Rol necesario para esta tarea (determina la tarifa de facturación)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="resources.role",
                        verbose_name="Rol Requerido",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Etapa a la que pertenece esta tarea",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="projects.stage",
                        verbose_name="Etapa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["-priority", "due_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Horas Trabajadas",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Auto-calculado: hours × resource.internal_cost",
                        max_digits=10,
                        verbose_name="Costo Interno (USD)",
                    ),
                ),
                (
                    "billable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Auto-calculado según tipo de proyecto",
                        max_digits=10,
                        verbose_name="Monto Facturable (USD)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción del Trabajo"),
                ),
                ("is_billable", models.BooleanField(default=True, verbose_name="Es Facturable")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Gestión, Reuniones, Overhead",
                        max_length=100,
                        verbose_name="Categoría",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="resources.resource",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Tiempo",
                "verbose_name_plural": "Entradas de Tiempo",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Horas Trabajadas",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Auto-calculado: hours × resource.internal_cost",
                        max_digits=10,
                        verbose_name="Costo Interno (USD)",
                    ),
                ),
                (
                    "billable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Auto-calculado: hours × task.required_role.standard_rate",
                        max_digits=10,
                        verbose_name="Monto Facturable (USD)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="¿Qué se hizo en estas horas?",
                        verbose_name="Descripción del Trabajo",
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True,
                        help_text="Si es False, no se factura al cliente (overhead interno)",
                        verbose_name="Es Facturable",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas Internas")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_logs",
                        to="resources.resource",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="projects.task",
                        verbose_name="Tarea",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Tiempo",
                "verbose_name_plural": "Registros de Tiempo",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["code"], name="projects_pr_code_80abae_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "is_active"], name="projects_pr_status_163197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["project_type"], name="projects_pr_project_573ce6_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["start_date", "end_date"], name="projects_pr_start_d_dfae95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["project", "status"], name="projects_st_project_5349d7_idx"),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["project", "order"], name="projects_st_project_22c2c2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="stage",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project", "status"], name="projects_ta_project_cd2085_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project", "stage"], name="projects_ta_project_5ea58c_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_resource", "status"], name="projects_ta_assigne_52bf4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="projects_ta_due_dat_4757e0_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["project", "date"], name="projects_ti_project_931a2e_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["resource", "date"], name="projects_ti_resourc_f2ea76_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["date"], name="projects_ti_date_338a02_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["task", "date"], name="projects_ti_task_id_60f435_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["resource", "date"], name="projects_ti_resourc_d1da40_idx"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["date"], name="projects_ti_date_5fde8c_idx"),
        ),
    ]
