# Generated by Django 5.2.10 on 2026-01-23 03:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("resources", "0002_alter_resource_options_remove_resource_full_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Fecha en que inicia la asignación",
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Fecha en que termina la asignación", verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "hours_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cuántas horas a la semana dedicará a este proyecto (máx 168h = 7×24h)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("168.00")),
                        ],
                        verbose_name="Horas por Semana",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si esta asignación está actualmente vigente",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones sobre esta asignación",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="resources.resource",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación",
                "verbose_name_plural": "Asignaciones",
                "ordering": ["-start_date", "resource"],
                "indexes": [
                    models.Index(
                        fields=["resource", "start_date", "end_date"],
                        name="projects_al_resourc_c8701f_idx",
                    ),
                    models.Index(
                        fields=["project", "start_date"], name="projects_al_project_fa13f5_idx"
                    ),
                    models.Index(fields=["is_active"], name="projects_al_is_acti_6f5c0e_idx"),
                ],
            },
        ),
    ]
