# Generated by Django 5.2.10 on 2026-02-14 18:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="budget_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo máximo permitido para el proyecto",
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Límite de Presupuesto Interno (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="fixed_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Solo para proyectos Fixed Price",
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Precio Fijo Acordado (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarifa aplicada al cliente en proyectos T&M",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Tarifa por Hora (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimación de techo para proyectos T&M",
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Presupuesto Máximo Estimado (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="billable_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Auto-calculado según tipo de proyecto",
                max_digits=10,
                verbose_name="Monto Facturable (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Auto-calculado: hours × resource.internal_cost",
                max_digits=10,
                verbose_name="Costo Interno (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="timelog",
            name="billable_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Auto-calculado: hours × task.required_role.standard_rate",
                max_digits=10,
                verbose_name="Monto Facturable (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="timelog",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Auto-calculado: hours × resource.internal_cost",
                max_digits=10,
                verbose_name="Costo Interno (COP)",
            ),
        ),
    ]
