# Generated by Django 5.2.10 on 2026-02-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_budget_limit_alter_project_fixed_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="manual_progress_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje de avance establecido manualmente (0-100)",
                max_digits=5,
                null=True,
                verbose_name="Porcentaje de Avance Manual (%)",
            ),
        ),
    ]
