# Generated by Django 5.2.10 on 2026-01-23 01:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: Senior Backend Developer, Junior QA Engineer",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre del Rol",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ej: SBE, JQA",
                        max_length=20,
                        unique=True,
                        verbose_name="Código del Rol",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering"),
                            ("design", "Design"),
                            ("product", "Product Management"),
                            ("qa", "Quality Assurance"),
                            ("devops", "DevOps"),
                            ("data", "Data Science"),
                            ("management", "Management"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "seniority",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid-Level"),
                            ("senior", "Senior"),
                            ("lead", "Tech Lead"),
                            ("architect", "Architect"),
                            ("principal", "Principal"),
                        ],
                        default="mid",
                        max_length=20,
                        verbose_name="Nivel de Seniority",
                    ),
                ),
                (
                    "standard_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tarifa usada para estimaciones y presupuestos al cliente",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Tarifa Estándar por Hora (USD)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descripción del Rol")),
                (
                    "required_skills",
                    models.JSONField(
                        default=list,
                        help_text="Lista de habilidades técnicas necesarias para este rol",
                        verbose_name="Habilidades Requeridas",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si este rol está disponible para asignación en estimaciones",
                        verbose_name="Rol Activo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas Internas")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["seniority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=20, unique=True, verbose_name="ID de Empleado"),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Nombre Completo")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Corporativo"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Teléfono")),
                (
                    "internal_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo real por hora de este recurso específico (confidencial)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Costo Interno por Hora (USD)",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Fecha de Contratación")),
                (
                    "skills_vector",
                    models.JSONField(
                        default=dict,
                        help_text="Diccionario de habilidades con nivel de competencia (1-5)",
                        verbose_name="Vector de Habilidades",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        default=list,
                        help_text="Lista de certificaciones profesionales",
                        verbose_name="Certificaciones",
                    ),
                ),
                (
                    "qdrant_point_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del vector embedding de este recurso en Qdrant",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="ID en Qdrant",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("partially_allocated", "Parcialmente Asignado"),
                            ("fully_allocated", "Totalmente Asignado"),
                            ("on_leave", "En Licencia"),
                            ("unavailable", "No Disponible"),
                        ],
                        default="available",
                        max_length=30,
                        verbose_name="Estado de Disponibilidad",
                    ),
                ),
                (
                    "availability_percentage",
                    models.IntegerField(
                        default=100,
                        help_text="Porcentaje de tiempo disponible para nuevas asignaciones (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="% Disponibilidad",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biografía Profesional")),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="resources/profiles/",
                        verbose_name="Foto de Perfil",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="Ubicación"),
                ),
                (
                    "preferred_technologies",
                    models.JSONField(default=list, verbose_name="Tecnologías Preferidas"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas Internas")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario del Sistema",
                    ),
                ),
                (
                    "primary_role",
                    models.ForeignKey(
                        help_text="Rol principal del recurso (determina capacidades)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="resources.role",
                        verbose_name="Rol Principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "ordering": ["full_name"],
            },
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["category", "seniority"], name="resources_r_categor_7072c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="resources_r_code_3bf16b_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["employee_id"], name="resources_r_employe_cfc1ea_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["email"], name="resources_r_email_7187af_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["status", "availability_percentage"], name="resources_r_status_e17634_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["primary_role", "is_active"], name="resources_r_primary_c5d832_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["qdrant_point_id"], name="resources_r_qdrant__4a6017_idx"),
        ),
    ]
