# Generated by Django 5.2.10 on 2026-01-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
            },
        ),
        migrations.RemoveField(
            model_name="resource",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="user",
        ),
        migrations.AddField(
            model_name="resource",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="Nombre"),
        ),
        migrations.AddField(
            model_name="resource",
            name="last_name",
            field=models.CharField(default="", max_length=100, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="hire_date",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de Contratación"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="skills_vector",
            field=models.JSONField(
                default=list,
                help_text="Lista de habilidades con nivel de competencia (1-5)",
                verbose_name="Vector de Habilidades",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="category",
            field=models.CharField(
                choices=[
                    ("management", "Management"),
                    ("technical", "Technical"),
                    ("business_analysis", "Business Analysis"),
                    ("qa", "QA/Testing"),
                    ("design", "Design"),
                    ("operations", "Operations"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="seniority",
            field=models.CharField(
                choices=[
                    ("entry", "Entry Level"),
                    ("junior", "Junior"),
                    ("mid", "Mid-Level"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                    ("principal", "Principal"),
                ],
                default="mid",
                max_length=20,
                verbose_name="Nivel de Seniority",
            ),
        ),
    ]
