# Generated by Django 5.2.10 on 2026-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_resource_options_remove_resource_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                help_text="Ej: SBE, JQA (obligatorio)",
                max_length=20,
                unique=True,
                verbose_name="Código del Rol",
            ),
        ),
    ]
