# Generated by Django 5.2.10 on 2026-02-14 18:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_alter_role_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="internal_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Costo real por hora de este recurso específico (confidencial)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Costo Interno por Hora (COP)",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="standard_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Tarifa usada para estimaciones y presupuestos al cliente",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Tarifa Estándar por Hora (COP)",
            ),
        ),
    ]
