# Generated by Django 5.2.10 on 2026-01-23 02:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("resources", "0002_alter_resource_options_remove_resource_full_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StandupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                ("date", models.DateField(verbose_name="Fecha del Standup")),
                (
                    "what_i_did",
                    models.TextField(
                        help_text="Resumen de actividades completadas",
                        verbose_name="¿Qué hice ayer?",
                    ),
                ),
                (
                    "what_i_will_do",
                    models.TextField(
                        help_text="Plan de trabajo para hoy", verbose_name="¿Qué haré hoy?"
                    ),
                ),
                (
                    "blockers",
                    models.TextField(
                        blank=True,
                        help_text="Impedimentos o problemas que enfrento",
                        verbose_name="Bloqueadores",
                    ),
                ),
                (
                    "hours_logged",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                        verbose_name="Horas Trabajadas",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Rango: -1 (muy negativo) a +1 (muy positivo)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Score de Sentimiento",
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positivo"),
                            ("neutral", "Neutral"),
                            ("negative", "Negativo"),
                            ("very_negative", "Muy Negativo"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Etiqueta de Sentimiento",
                    ),
                ),
                (
                    "sentiment_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Nivel de confianza del modelo NLP (0-1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Confianza del Análisis",
                    ),
                ),
                (
                    "detected_entities",
                    models.JSONField(
                        default=list,
                        help_text="Términos técnicos o conceptos extraídos por NLP",
                        verbose_name="Entidades Detectadas",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords principales del texto",
                        verbose_name="Palabras Clave",
                    ),
                ),
                (
                    "has_blockers",
                    models.BooleanField(default=False, verbose_name="Tiene Bloqueadores"),
                ),
                (
                    "blocker_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Severidad del Bloqueador",
                    ),
                ),
                (
                    "requires_attention",
                    models.BooleanField(
                        default=False,
                        help_text="Flag automático si el sentimiento es muy negativo o hay bloqueadores críticos",
                        verbose_name="Requiere Atención",
                    ),
                ),
                (
                    "nlp_processed",
                    models.BooleanField(default=False, verbose_name="Procesado por NLP"),
                ),
                (
                    "nlp_processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Procesamiento NLP"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas Adicionales")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standups",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standups",
                        to="resources.resource",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standup Log",
                "verbose_name_plural": "Standup Logs",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource", "date"], name="standups_st_resourc_200117_idx"
                    ),
                    models.Index(fields=["project", "date"], name="standups_st_project_439811_idx"),
                    models.Index(
                        fields=["sentiment_label", "requires_attention"],
                        name="standups_st_sentime_63fdc7_idx",
                    ),
                    models.Index(fields=["has_blockers"], name="standups_st_has_blo_d28899_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "project", "date"),
                        name="unique_standup_per_resource_project_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamMood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "average_sentiment",
                    models.FloatField(
                        help_text="Promedio de sentiment_score del equipo",
                        verbose_name="Sentimiento Promedio",
                    ),
                ),
                (
                    "team_size",
                    models.IntegerField(
                        help_text="Cantidad de standups ese día",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tamaño del Equipo",
                    ),
                ),
                (
                    "positive_count",
                    models.IntegerField(default=0, verbose_name="Standups Positivos"),
                ),
                (
                    "neutral_count",
                    models.IntegerField(default=0, verbose_name="Standups Neutrales"),
                ),
                (
                    "negative_count",
                    models.IntegerField(default=0, verbose_name="Standups Negativos"),
                ),
                (
                    "blocker_count",
                    models.IntegerField(default=0, verbose_name="Total de Bloqueadores"),
                ),
                (
                    "critical_blocker_count",
                    models.IntegerField(default=0, verbose_name="Bloqueadores Críticos"),
                ),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("improving", "Mejorando"),
                            ("stable", "Estable"),
                            ("declining", "Declinando"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tendencia",
                    ),
                ),
                (
                    "common_keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords más frecuentes en los standups del día",
                        verbose_name="Keywords Comunes",
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[("green", "Verde"), ("yellow", "Amarillo"), ("red", "Rojo")],
                        default="green",
                        max_length=20,
                        verbose_name="Nivel de Alerta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_moods",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mood del Equipo",
                "verbose_name_plural": "Moods del Equipo",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["project", "date"], name="standups_te_project_9821c4_idx"),
                    models.Index(fields=["alert_level"], name="standups_te_alert_l_249797_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "date"), name="unique_team_mood_per_project_date"
                    )
                ],
            },
        ),
    ]
